topics:
- name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 100
- name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 20
- name    : move_base
  topic   : move_base/cmd_vel
  timeout : 0.5
  priority: 10
- name    : robot_wandering_node
  topic   : wandering/cmd_vel
  timeout : 0.5
  priority: 2

locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0    
  priority: 255